### PR TITLE
Patch including @Rid and acme-0.8 update

### PR DESCRIPTION
**Pull request by pasgou**
Update including @Rid and @alastaircoote works and my contribution to make image smaller using only the acme-0.8 branch of simp_le project.

### CODE REVIEW

**Comment by JrCs** [comment]
Please made only ONE PR by functionnality/fix.

Can split and rebase your work to multiple PR ?

Thanks.

**Comment by pasgou** [comment]
I ma sorry to not know how to do that.

**Comment by JrCs** [comment]
Seems all the patchs are already merged.
Only the docker-gen-multi not merged.

**Comment by pasgou** [comment]
But for this one, I don't know if it works. Pay attention.

**Pull request closed without merging**
