### PR TITLE
Added $DH_PARAM_BITS evironment var

### PR DESCRIPTION
**Pull request by kije**
Gives the user of the image the ability to specify how strong the generated dhparams should be

### CODE REVIEW

**Comment by briceburg** [comment]
LGTM -- any worry about merging?

**Comment by JrCs** [comment]
Need to check if we can use "any number" for DH size.

**Comment by JrCs** [comment]
@briceburg what is your use case to need to change the number of bits for DH keys. It's already 4096 and give use a A+ grade on  Qualsys SSL Server Test ?

**Comment by JrCs** [comment]
No more info. Closing this PR

**Pull request closed without merging**
